---
- name: set proxy env variable
  hosts: dev
  become: true
  tasks:
          - name: set env proxy variable
            yum:
                    name: psmisc
                    state: present
            environment:
                    http_proxy: http://proxy.example.com:8080
