---
- hosts: dev
  become: true
  become_user: root
  tasks:
      - name: ensure directory exists
        file:
           path: /tmp/test_dir
           state: directory
      - name: run the command in different directory
        command: touch test_file3
        args:
           chdir: /tmp/test_dir
