---
- name: working with map attribute
  hosts: dev
  vars:
       names: [ {
        "first": "Paul",
        "last": "Thompson",
        "mobile": "+1-234-31245543",
        "ctc": "100000",
        "address": {
          "city": "LasVegas",
          "country": "USA"
        }
      },
      {
        "first": "Rod",
        "last": "Johnson",
        "mobile": "+1-584-31551209",
        "ctc": "300000",
        "address": {
          "city": "Boston",
          "country": "USA"
        }
      },
      {
        "first": "Sarav",
        "last": "AK",
        "mobile": "+919876543210",
        "ctc": "200000",
        "address": {
          "city": "Chennai",
          "country": "India"
        }
      }]
  tasks:
          - name: print only city
            debug:
                    msg: "{{ names | map(attribute='address') | map(attribute='city') | list }}"
          - name: print only country
            debug:
                    msg: "{{ names | map(attribute='address') | map(attribute='country') | list }}"
          - name: print only modbile numbers
            debug:
                    msg: "{{ names | map(attribute='mobile') | join(',') }}"
          - name: convert letters to uppercase
            debug:
                    msg: "{{ names | map(attribute='first') | map('upper') | list }}"
          - name: convert the CTC value to float value
            debug:
                    msg: "{{ names | map(attribute='ctc') | map('float') | list }}"
          - name: appending USD to CTC value
            debug:
                    msg: "{{ names | map(attribute='ctc') | product(['USD']) | map('join',' ') | list }}"
                   
