---
- hosts: dev
  become: true
  become_user: root
  tasks:
          - name: get hostname
            command: hostname -s
            register: command_output
          - name: show command output
            debug:
                    var: command_output
