---
- hosts: dev
  become: true
  become_user: root
  tasks:
          - name: explore register
            command: hostname -s
            when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version | int >= 5 ) or ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 18 )
            register: hostname_output
          - debug:
                  var: hostname_output.stdout
