---
- hosts: dev
  become: true
  become_user: root
  tasks:
          - name: get hostname
            command: hostname -s
            when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
            register: command_output
          - debug:
               var: command_output.stdout
