---
- hosts: dev
  become: yes
  become_user: root
  tasks:
      - name: restart ens33 network
        service:
              name: NetworkManager
              state: restarted
              args: enp0s3
