---
- name: restart a service which is in /etc/init.d
  hosts: localhost
  become: true
  tasks:
          - name: restart dbus service
            service:
                    name: dbus
                    pattern: /etc/init.d/dbus
                    state: started
