---
- hosts: dev
  become: true
  become_user: root
  tasks:
      - name: copy multiple files with loop
        copy: 
           src: "{{ item }}"
           dest: "/home/ansible/{{ item }}"
        loop:
           - test_file1
           - test_file2
