---
- hosts: dev
  tasks:
      - name: ensure directory exists
        file:
           path: $HOME/test_directory
           state: directory
      - name: remove directory
        file:
           path: $HOME/test_directory
           state: absent
