---
- name: execute command on ansible controller
  hosts: dev
  vars:
     ansible_connection: local
     ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
       - name: debug message
         debug:
           msg: "{{ ansible_hostname }}"
