---
- hosts: dev
  tasks:
      - name: Replace a line in file
        become: yes
        become_user: root
        lineinfile:
                 path: /home/{{ ansible_user }}/test_file.txt
                 #The string to search
                 regexp: "LogLevel warn"
                 #The string to Replace
                 line: "LogLevel debug"
                 state: present
                 backup: yes
        when: ansible_distribution == "CentOS"
        register: example
      - debug: var=example.stdout