---
- name: user module demo
  hosts: dev
  become: true
  vars:
          myuser: "techie"
          mypassword: "Linux@123"
  tasks:
          - name: change user password
            user:
                    name: "{{ myuser }}"
                    password: "{{ mypassword | password_hash('sha512','salt') }}"
                    state: present
