---
- name: user module demo
  hosts: dev
  vars:
          myuser: "techie"
  become: true
  tasks:
          - name: lock user password
            user:
                    name: "{{ myuser }}"
                    state: present
                    password_lock: true
                    shell: "/sbin/nologin"
