---
- name: user module demo
  hosts: dev
  vars:
          myuser: "techie"
  become: true
  tasks:
          - name: unlock user password
            user:
                    name: "{{ myuser }}"
                    state: present
                    password_lock: false
                    shell: "/bin/bash"
