---
- name: user module demo
  hosts: dev
  vars:
          myuser: "techie"
  become: true
  tasks:
          - name: user password expiration
            user:
                    name: "{{ myuser }}"
                    password_expire_min: 1
                    password_expire_max: 90
