---
- name: run command in localhost
  hosts: dev
  tasks:
          - name: print hostname
            command: hostname
            delegate_to: 127.0.0.1
            register: comm_output
          - debug:
                  msg: "{{ comm_output.stdout_lines }}"

