#It is possible to insert/update/remove a block of multiline text surrounded by customizable marker lines

---
- name: insert multiple lines
  hosts: dev
  become: true
  tasks:
          - name: blockinfile module demo
            blockinfile:
                    dest: /etc/test_file
                    state: present
                    create: yes
                    content: |
                            192.168.0.0 example.com     example.com
                            192.168.0.1 example.com     example.com
