---
- name: rename file or directory
  hosts: dev
  vars:
          mysrc: "/home/ansible/testfile"
          mydest: "/home/ansible/newfilename"
  tasks:
          - name: check if file exists
            stat:
                    path: "{{ mysrc }}"
            register: check_file_name
          - name: print debug
            debug:
                    var: check_file_name
          - name: copy file with new name
            copy:
                    src: "{{ mysrc }}"
                    remote_src: yes
                    dest: "{{ mydest }}"
            when: check_file_name.stat.exists
          - name: Remove old file
            file:
                    dest: "{{ mysrc }}"
                    state: absent
            when: check_file_name.stat.exists
