---
- name: file module demo
  hosts: dev
  vars:
          myfile: "/home/ansible/newfile"
  tasks:
          - name: file "{{ myfile }}" not present
            file:
                    path: "{{ myfile }}"
                    state: absent
