---
- name: delete files in dir demo
  hosts: dev
  vars:
          mypath: "/home/ansible/example-bkp"
  tasks:
          - name: collect files
            find:
                    paths: "{{ mypath }}"
                    hidden: true
                    recurse: true
                    file_type: any
            register: collected_files
          - name: remove collected files
            file:
                    path: "{{ item.path }}"
                    state: absent
            with_items:
                    - "{{ collected_files.files }}"
