#I haven't tried this playbook
---
- name: disk demo
  hosts: dev
  become: true
  tasks:
          - name: create partition
            parted:
                    device: /dev/sdb
                    number: 1
                    flags: [ lvm ]
                    state: present
