---
- name: get_url module demo
  hosts: dev
  vars:
          myurl: "https://releases.ansible.com/ansible/ansible-2.9.25.tar.gz"
          mydest: "/home/ansible"
  tasks:
          - name: download file
            get_url:
                    url: "{{ myurl }}"
                    dest: "{{ mydest }}"
                    mode: 0777
                    owner: ansible
                    group: ansible

